### ISSUE TITLE
Explore providing localized properties using separate file

### ISSUE THREAD

**Issue by yuriys-kentico** [Kentico/KInspector#273]
### Motivation

Currently the properties **Name**, **ShortDescription**, and **LongDescription** are embedded in English HTML in each report class. This makes the code dependent on these hard-coded values and prevents quick modification or localization. Also, the HTML should be abstracted into a markup language like Markdown to make it presentation-agnostic.

### Proposed solution

Expose the properties in a separate file. Two ideas:

Use Markdown headings to separate the file into a predictable structure: one line using one heading to be the name, another line using a second heading to be the short description, and the rest of the file for the long description. 

Use a JSON file with properties containing the Markdown. The disadvantage is that it will make it harder to preview using modern code editors. The advantage is that it will be easier to extend the structure and make it more portable.

**Comment by ChristopherJennings** [comment]
On first blush, I'd recommend we explore markdown with YAML front matter. This is common and probably provides us with the needed flexibility. What do you think?

**Comment by yuriys-kentico** [comment]
YAML sounds good. Some combination of the following might be useful: [CommonMark.NET](https://github.com/Knagis/CommonMark.NET) and [YamlDotNet](https://github.com/aaubry/YamlDotNet)

**Comment by yuriys-kentico** [comment]
I also realized this should be expanded to include text for use within the report dynamically. There would be a signature like this:
```csharp
Comment ICommentService.Get(string commentName)
```
And class like:
```csharp
class Comment {
  public string Text;
}
```

The _ReportName.en-US.yaml_ could look like this:
```yaml
names:
  short: "Name"
descriptions:
  short: "This report checks the user data."
  long: |
    "This report checks the database tables **CMS_User** and **CMS_UserSettings** for inconsistencies."
comments:
  invalidUser: "This user is invalid."
  complexExplanation: >
    "No users with passwords found. This is a *major* security hole."
```

The names and descriptions should not be available in the report and would be handled in the background at some point in the initialization.
